### ISSUE TITLE
webpack devserver build error

### ISSUE THREAD

**Issue by isjulianj** [bricewilson/TypeScript-Getting-Started#1]
I'm in the module: Installing TypeScript and Configuring a Project

I'm on the video: Configuring Compiler Options in tsconfig.json

I got a build error when running 'yarn start' from webpack devserver when using the null assertion operator, to fix it I had to install ts-loader into my dev dependencies and then add ts-loader to my webpack config. 

  module.exports = {
  entry: './app/app.ts',
  devtool: 'inline-source-map',
  resolve: {
    extensions: ['.tsx', '.ts', '.js']
  },
  **module: {
    rules: [{ test: /\.tsx?$/, loader: 'ts-loader' }]
  },**
  output: {
    filename: 'bundle.js'
  },
  devServer: {
    inline: false
  }
};

**Comment by isjulianj** [comment]
Worked through a bit more and see you add it later. It's just we're introduced to the start Script just before.

**Comment by bricewilson** [comment]
I'm glad you worked through it. The lesson for me is that I probably should have included it earlier or at least mentioned that it would be installed soon. Thanks!
