### ISSUE TITLE
sign in

### ISSUE THREAD

**Issue by ace540i** [bricewilson/TypeScript-Getting-Started#5]
Hi, 
I've cloned master branch and when i start server and go to localhost/8080 it prompts for sign in. 
what are credentials?
Thanks,
Mike

**Comment by bricewilson** [comment]
Hey @ace540i. There are no credentials required to run the demo app. The first two demos in the course module titled "Installing TypeScript and Configuring a Project" show you how to get the demo app running. If you're still being prompted for credentials, it may be that you already have some other app running on port 8080.

I hope that helps!

Brice
